### ISSUE TITLE
Open Letter to Markus Löning (mloning) concerning his intention to decommission sktime on pypi

### ISSUE THREAD

**Issue by JonathanBechtel** [sktime/community-org#48] opened 2023-03-15 21:05 UTC
Dear Markus,

We – the sktime user and contributor community represented by the sktime council – would like to thank you for your former contributions to sktime and setting up of its digital infrastructure.

For us, sktime has been a high-value, high-impact, reliably maintained piece of software. You and the other sktime developers can be proud of what you have created. For the future, reliability and continuity of sktime are of particular importance to us, and we are enthusiastic to participate in sktime’s governance under its new, widened community model.

In this vein, we would kindly ask you to hand the sktime pypi project to us. We appreciate that there have been recent disagreements between some developers of sktime, but please consider that the wider sktime community are neither involved, nor interested in this conflict. The council’s main commitment is to good and transparent governance of sktime, its reliability as a package, and a healthy community that is open to all.

We acknowledge your concerns, and are keen to help resolve the situation. At the same time, we have to firmly and formally state that: only a hand-over of the sktime pypi project to us – sktime – has our consent. Any other actions (e.g., destruction/”deprecation”) are expressly against our will and do not have our consent, as they are fundamentally against interests of the users of sktime and contributors to sktime. We are in particular concerned about wide-spread harm to dependent software and the unnecessary work your actions would cause to dependent developers.

We are open to discuss the terms of a hand-over transparently, in a public, minuted meeting, e.g., this Friday, March 17, in our regular council meeting at 5pm UTC.  Please do not hesitate to reach out to us, in public response to this letter.

Signed: sktime council & community members

**Comment by marrov** [comment] 2023-03-16 06:53
Signed

**Comment by chillerobscuro** [comment] 2023-03-17 20:32
Signed, there has been no back and forth on the "Community consultation" issue, just updates based on conversations that seem to be happening in private? Would really appreciate an actual discussion on a minuted meeting, where the concerns from prior contributors are addressed.

**Comment by fkiraly** [comment] 2023-03-17 22:35
@chillerobscuro, there are no private conversations happening with Markus at the moment. The council is committed to transparency, i.e., having the discourse in public and visible to the community as much as possible. Markus insists on having some communication in private, the council will have to deliberate on this.

The first we heard from Markus since then in an open space is, he showed up unannounced in the council meeting today - this is minuted, just moved the minutes (to be confirmed Mar 24) here: https://github.com/sktime/community-org/blob/main/community_council/previous_meetings/20230317-meeting.md

If I were to summarize the discussion with Markus, he was saying:

* "I have made my decision"
* "but I don't want to discuss this ins public"
* "also, I have had secret/private discussions with sktime community members who told me they were in favour of blocking sktime from pypi"

The council will have to decide how to proceed from this.

**Comment by fkiraly** [comment] 2023-03-17 22:35
also, Signed

**Comment by hazrulakmal** [comment] 2023-03-22 14:18
Signed

**Comment by fkiraly** [comment] 2023-08-20 23:48
The situation has ended, after legal action Markus has returned the misappropriated pypi account and signed an agreement to not claim anymore that the sktime project is defunct.

**Closed** 2023-08-20 23:48 UTC
